### ISSUE TITLE
flex 实现不同的排序

### ISSUE THREAD

**Issue by JackFGreen** [JackFGreen/blog#14]
# flex 实现不同的排序

## 底部往上排序
block 元素，默认从上往下

```html
<ul class="list">
  <li class="list-item">1</li>
  <li class="list-item">2</li>
  <li class="list-item">3</li>
</ul>
```

```css
.list {
  height: 200px;
  display: flex;
  // 换行
  flex-wrap: wrap;
  // 从 flex 盒子底部开始
  align-content: flex-end;
}
.list-item {
  // 占据整行宽度，配合 flex-wrap
  width: 100%;
}
```
