### ISSUE TITLE
双飞翼布局

### ISSUE THREAD

**Issue by JackFGreen** [JackFGreen/blog#21]
# 双飞翼布局
![image](https://user-images.githubusercontent.com/23187848/43248245-d5db3244-90e9-11e8-8597-40572d984b4f.png)

## 传统布局
```html
<div class="container">
  <!-- middle 需要最先渲染 -->
  <div class="middle">
    <div class="inner">middle</div>
  </div>
  <div class="left">left
    <p>line2</p>
  </div>
  <div class="right">right</div>
</div>
```
```css
* {
  margin: 0;
  padding: 0;
}
.middle {
  float: left;
  width: 100%;
  background: pink;
}
.middle .inner {
  margin-left: 200px;
  margin-right: 400px;
  text-align: center;
}
.left {
  float: left;
  width: 200px;
  background: red;
  margin-left: -100%;
}
.right {
  float: right;
  width: 400px;
  background: yellow;
  margin-left: -400px;
}
/* 等高 */
.middle, .left, .right {
  padding-bottom: 100%;
  margin-bottom: -100%;
}
.container {
  overflow: hidden;
}
```

## flex 布局
```html
<div class="container">
  <!-- middle 需要最先渲染 -->
  <div class="middle">middle</div>
  <div class="left">left
    <p>line2</p>
  </div>
  <div class="right">right</div>
</div>
```
```css
* {
  margin: 0;
  padding: 0;
}
.container {
  display: flex;
}
.middle {
  background: pink;
  flex: 1;
}
.left {
  width: 200px;
  background: red;
  order: -1;
}
.right {
  width: 400px;
  background: yellow;
}
```
