### ISSUE TITLE
input 自动填充

### ISSUE THREAD

**Issue by JackFGreen** [JackFGreen/blog#23]
# input 自动填充

```html
<input type="text" readonly onfocus="this.removeAttribute('readonly');">

<!-- 记住密码功能失效 -->
<input type="password" autocomplete="new-password">
```

```css
/* 去掉黄色背景 */
input:-webkit-autofill {
  box-shadow: 0 0 0 1000px #fff inset
}
```
